version: 2.1

orbs:
  python: circleci/python@1.5.0

jobs:
  manylinux2014-aarch64:
    parameters:
      cibw_build:
        type: string
        default: "cp37-*"

    machine:
      image: ubuntu-2004:202101-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run:
          name: Install dependencies
          command: |
             sudo apt-get update && sudo apt-get -y install python3 python3-pip 
             pip install --upgrade pip
             python setup.py install 
             python -m pip install --upgrade pip
             pip install setuptools wheel twine
             python setup.py sdist bdist_wheel
             pip install pytest sybil flaky sklearn dill
             pytest
workflows:
  version: 2.1
  main:
    jobs:
      - manylinux2014-aarch64:
          matrix:
            parameters:
              cibw_build:
                - "cp37*"
